app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lcd_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Controller/APIController.php"
    methods:  [GET, POST, PUT, DELETE, OPTIONS]